# Generated by Django 6.0.7 on 2026-08-02 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Official employee ID (e.g., EMP-001)', max_length=50, unique=True, verbose_name='Employee ID')),
                ('designation', models.CharField(blank=True, help_text='Job title or designation (e.g., Software Engineer)', max_length=100, null=True, verbose_name='Designation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('department', models.ForeignKey(blank=True, help_text='Department this employee belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='departments.department', verbose_name='Department')),
                ('user', models.OneToOneField(help_text='The user account for this employee', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'verbose_name_plural': 'Employee Profiles',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_id', models.CharField(help_text='Official technician ID (e.g., TECH-001)', max_length=50, unique=True, verbose_name='Technician ID')),
                ('specialization', models.CharField(blank=True, help_text='Area of expertise (e.g., Hardware, Networking, Software)', max_length=200, null=True, verbose_name='Specialization')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('department', models.ForeignKey(blank=True, help_text='Department this technician belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicians', to='departments.department', verbose_name='Department')),
                ('user', models.OneToOneField(help_text='The user account for this technician', on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Technician Profile',
                'verbose_name_plural': 'Technician Profiles',
                'ordering': ['technician_id'],
            },
        ),
    ]
