# Generated by Django 6.0.7 on 2026-08-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employeeprofile_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Official employee ID (e.g., EMP-001)', max_length=50, null=True, unique=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='technician_id',
            field=models.CharField(blank=True, help_text='Official technician ID (e.g., TECH-001)', max_length=50, null=True, unique=True, verbose_name='Technician ID'),
        ),
    ]
