# Generated by Django 6.0.7 on 2026-09-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_account_status_user_rejection_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ID Counter',
                'verbose_name_plural': 'ID Counters',
            },
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Auto-generated (EMP-000001)', max_length=50, null=True, unique=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='technician_id',
            field=models.CharField(blank=True, help_text='Auto-generated (TECH-000001)', max_length=50, null=True, unique=True, verbose_name='Technician ID'),
        ),
    ]
