# Generated by Django 6.0.7 on 2026-08-02 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(help_text='Name of the asset (e.g., Dell Latitude 5520)', max_length=200, verbose_name='Asset Name')),
                ('asset_code', models.CharField(help_text='Unique asset code (e.g., AST-0001)', max_length=50, unique=True, verbose_name='Asset Code')),
                ('brand', models.CharField(blank=True, help_text='Brand/Manufacturer (e.g., Dell, HP, Lenovo)', max_length=100, null=True, verbose_name='Brand')),
                ('model', models.CharField(blank=True, help_text='Model number or name', max_length=100, null=True, verbose_name='Model')),
                ('purchase_date', models.DateField(blank=True, help_text='Date when the asset was purchased', null=True, verbose_name='Purchase Date')),
                ('warranty_expiry', models.DateField(blank=True, help_text='Date when the warranty expires', null=True, verbose_name='Warranty Expiry Date')),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('in_repair', 'In Repair'), ('disposed', 'Disposed')], default='available', help_text='Current status of the asset', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['asset_code'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the asset category (e.g., Laptop, Desktop, Printer)', max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, help_text='Brief description of this category', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(help_text='Date when the asset was assigned', verbose_name='Assigned Date')),
                ('return_date', models.DateField(blank=True, help_text='Date when the asset was returned (if returned)', null=True, verbose_name='Return Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned')], default='active', help_text='Current status of this assignment', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('asset', models.ForeignKey(help_text='The asset being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset', verbose_name='Asset')),
                ('employee', models.ForeignKey(help_text='The employee the asset is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Asset Assignment',
                'verbose_name_plural': 'Asset Assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetcategory', verbose_name='Category'),
        ),
    ]
