# Generated by Django 6.0.7 on 2026-08-20 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_serial_number_alter_asset_asset_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
    ]
