# Generated by Django 6.0.7 on 2026-08-11 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0004_alter_ticket_assigned_at_alter_ticket_assigned_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title of the notification', max_length=200, verbose_name='Title')),
                ('message', models.TextField(help_text='Detailed message', verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('ticket_created', 'Ticket Created'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_status', 'Ticket Status Updated'), ('ticket_comment', 'Ticket Comment'), ('ticket_reopened', 'Ticket Reopened'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_closed', 'Ticket Closed'), ('feedback_received', 'Feedback Received'), ('asset_assigned', 'Asset Assigned'), ('asset_returned', 'Asset Returned'), ('general', 'General')], default='general', help_text='Category of this notification', max_length=30, verbose_name='Type')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read this notification', verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('ticket', models.ForeignKey(blank=True, help_text='Optional related ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tickets.ticket', verbose_name='Related Ticket')),
                ('user', models.ForeignKey(help_text='The user who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
