# Generated by Django 6.0.7 on 2026-08-16 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text='Master toggle for all email notifications', verbose_name='Email Notifications')),
                ('ticket_assignment', models.BooleanField(default=True, help_text='Notify when a ticket is assigned to you', verbose_name='Ticket Assignment')),
                ('ticket_status_update', models.BooleanField(default=True, help_text='Notify when a ticket status changes', verbose_name='Ticket Status Updates')),
                ('comment_notifications', models.BooleanField(default=True, help_text='Notify when someone comments on your tickets', verbose_name='Comment Notifications')),
                ('sla_alerts', models.BooleanField(default=True, help_text='Notify when SLA is at risk or breached', verbose_name='SLA Alerts')),
                ('asset_notifications', models.BooleanField(default=True, help_text='Notify when assets are assigned or returned', verbose_name='Asset Notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(help_text='The user who owns these preferences', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
