# Generated by Django 6.0.7 on 2026-08-02 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the issue category (e.g., Hardware, Software, Network)', max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, help_text='Brief description of this category', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Issue Category',
                'verbose_name_plural': 'Issue Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, help_text='Auto-generated unique ticket number', max_length=20, unique=True, verbose_name='Ticket Number')),
                ('title', models.CharField(help_text='Brief title describing the issue', max_length=200, verbose_name='Title')),
                ('description', models.TextField(help_text='Detailed description of the issue', verbose_name='Description')),
                ('screenshot', models.ImageField(blank=True, help_text='Attach a screenshot of the issue (optional)', null=True, upload_to='ticket_screenshots/', verbose_name='Screenshot')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Select the priority level', max_length=20, verbose_name='Priority')),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('reopened', 'Reopened'), ('closed', 'Closed')], default='open', help_text='Current status of the ticket', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_technician', models.ForeignKey(blank=True, help_text='Technician assigned to resolve this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Technician')),
                ('category', models.ForeignKey(blank=True, help_text='Issue category for this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.issuecategory', verbose_name='Category')),
                ('department', models.ForeignKey(blank=True, help_text='Department this ticket belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='departments.department', verbose_name='Department')),
                ('employee', models.ForeignKey(help_text='The employee who created this ticket', on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Write your comment here', verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('ticket', models.ForeignKey(help_text='The ticket this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket', verbose_name='Ticket')),
                ('user', models.ForeignKey(help_text='The user who wrote this comment', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ticket Comment',
                'verbose_name_plural': 'Ticket Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
