# Generated by Django 6.0.7 on 2026-08-04 07:55

import tickets.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Attach a screenshot of the issue (JPG/PNG, Max 2MB)', null=True, upload_to='ticket_screenshots/', validators=[tickets.validators.validate_screenshot], verbose_name='Screenshot'),
        ),
    ]
