# Generated by Django 6.0.7 on 2026-08-05 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_screenshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when ticket was assigned', null=True, verbose_name='Assigned At'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Admin who assigned this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reopen_reason',
            field=models.TextField(blank=True, help_text='Reason provided by employee for reopening', null=True, verbose_name='Reopen Reason'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when technician resolved the ticket', null=True, verbose_name='Resolved At'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, help_text='Auto-calculated based on priority', null=True, verbose_name='SLA Deadline'),
        ),
    ]
