# Generated by Django 6.0.7 on 2026-08-05 06:40

import django.db.models.deletion
import tickets.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('tickets', '0003_ticket_assigned_at_ticket_assigned_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assigned At'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Technician'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.issuecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='departments.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reopen_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reopen Reason'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resolved At'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_screenshots/', validators=[tickets.validators.validate_screenshot], verbose_name='Screenshot'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA Deadline'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('reopened', 'Reopened'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Ticket Number'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
