# Generated by Django 6.0.7 on 2026-08-29 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetcategory_created_at'),
        ('tickets', '0004_alter_ticket_assigned_at_alter_ticket_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='assets.asset', verbose_name='Affected Asset'),
        ),
    ]
