# Generated by Django 6.0.7 on 2026-08-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('technician', 'Technician'), ('both', 'Both')], default='both', help_text='Which role can use this department', max_length=20, verbose_name='Department Type'),
        ),
    ]
