# Generated by Django 6.0.7 on 2026-08-02 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], default=3, help_text='Rate the service from 1 (Very Poor) to 5 (Excellent)', verbose_name='Rating')),
                ('review', models.TextField(blank=True, help_text='Write your detailed review (optional)', null=True, verbose_name='Review')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('employee', models.ForeignKey(help_text='The employee giving this feedback', on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('ticket', models.ForeignKey(help_text='The ticket this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
                'unique_together': {('ticket', 'employee')},
            },
        ),
    ]
